---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netshoot
  labels:
    app: netshoot
    vrf: vrf1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netshoot
      vrf: vrf1
  template:
    metadata:
      labels:
        app: netshoot
        vrf: vrf1
    spec:
      containers:
        - name: netshoot-1
          image: nicolaka/netshoot
          command: ["/bin/bash"]
          args: ["-c", "while true; do ping localhost; sleep 60;done"]
